[package]
name = "balatrust_widgets"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { workspace = true }
crossterm = { workspace = true }
tachyonfx = { workspace = true }
balatrust_core = { path = "../balatrust_core" }
